/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'created_at' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'image' : ExternalBlob,
});
export const JoinSubmission = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'submitted_at' : IDL.Int,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  '_registerAsPresident' : IDL.Func([], [], []),
  'addAssistantAdmin' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createArticle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [Article],
      [],
    ),
  'deleteArticle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdminList' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJoinSubmissions' : IDL.Func([], [IDL.Vec(JoinSubmission)], ['query']),
  'getPresidentPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getRecentArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAssistantAdmin' : IDL.Func([IDL.Principal], [], []),
  'submitJoinForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'togglePublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateArticle' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'created_at' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'image' : ExternalBlob,
  });
  const JoinSubmission = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'submitted_at' : IDL.Int,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    '_registerAsPresident' : IDL.Func([], [], []),
    'addAssistantAdmin' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createArticle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [Article],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdminList' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat], [IDL.Opt(Article)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJoinSubmissions' : IDL.Func([], [IDL.Vec(JoinSubmission)], ['query']),
    'getPresidentPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getRecentArticles' : IDL.Func([IDL.Nat], [IDL.Vec(Article)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAssistantAdmin' : IDL.Func([IDL.Principal], [], []),
    'submitJoinForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'togglePublished' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateArticle' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };