/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'created_at' : bigint,
  'excerpt' : string,
  'category' : string,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface JoinSubmission {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'submitted_at' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<
    [string, string, string, ExternalBlob, string],
    Article
  >,
  'deleteArticle' : ActorMethod<[bigint], boolean>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getArticleById' : ActorMethod<[bigint], [] | [Article]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJoinSubmissions' : ActorMethod<[], Array<JoinSubmission>>,
  'getPublishedArticles' : ActorMethod<[], Array<Article>>,
  'getRecentArticles' : ActorMethod<[bigint], Array<Article>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitJoinForm' : ActorMethod<[string, string, string, string], undefined>,
  'togglePublished' : ActorMethod<[bigint], boolean>,
  'updateArticle' : ActorMethod<
    [bigint, string, string, string, ExternalBlob, string],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];